/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CapitalStressEngine {
  export type MarketExposureStruct = {
    marketId: BytesLike;
    grossLongNotional: BigNumberish;
    grossShortNotional: BigNumberish;
    openInterestCap: BigNumberish;
    maintenanceCollateral: BigNumberish;
    liquidCollateral: BigNumberish;
    liquidityDepth: BigNumberish;
    liquidationQueue: BigNumberish;
    fundingReceivable: BigNumberish;
    fundingPayable: BigNumberish;
    largestAccountNotional: BigNumberish;
    oracleConfidenceBps: BigNumberish;
  };

  export type MarketExposureStructOutput = [
    marketId: string,
    grossLongNotional: bigint,
    grossShortNotional: bigint,
    openInterestCap: bigint,
    maintenanceCollateral: bigint,
    liquidCollateral: bigint,
    liquidityDepth: bigint,
    liquidationQueue: bigint,
    fundingReceivable: bigint,
    fundingPayable: bigint,
    largestAccountNotional: bigint,
    oracleConfidenceBps: bigint
  ] & {
    marketId: string;
    grossLongNotional: bigint;
    grossShortNotional: bigint;
    openInterestCap: bigint;
    maintenanceCollateral: bigint;
    liquidCollateral: bigint;
    liquidityDepth: bigint;
    liquidationQueue: bigint;
    fundingReceivable: bigint;
    fundingPayable: bigint;
    largestAccountNotional: bigint;
    oracleConfidenceBps: bigint;
  };

  export type StressPolicyStruct = {
    priceShockBps: BigNumberish;
    liquidationHaircutBps: BigNumberish;
    liquidityHaircutBps: BigNumberish;
    fundingShockBps: BigNumberish;
    concentrationAddonBps: BigNumberish;
    minimumCoverageBps: BigNumberish;
    watchCoverageBps: BigNumberish;
    maxOpenInterestBps: BigNumberish;
    maxConcentrationBps: BigNumberish;
    minOracleConfidenceBps: BigNumberish;
  };

  export type StressPolicyStructOutput = [
    priceShockBps: bigint,
    liquidationHaircutBps: bigint,
    liquidityHaircutBps: bigint,
    fundingShockBps: bigint,
    concentrationAddonBps: bigint,
    minimumCoverageBps: bigint,
    watchCoverageBps: bigint,
    maxOpenInterestBps: bigint,
    maxConcentrationBps: bigint,
    minOracleConfidenceBps: bigint
  ] & {
    priceShockBps: bigint;
    liquidationHaircutBps: bigint;
    liquidityHaircutBps: bigint;
    fundingShockBps: bigint;
    concentrationAddonBps: bigint;
    minimumCoverageBps: bigint;
    watchCoverageBps: bigint;
    maxOpenInterestBps: bigint;
    maxConcentrationBps: bigint;
    minOracleConfidenceBps: bigint;
  };

  export type MarketAssessmentStruct = {
    marketId: BytesLike;
    grossOpenInterest: BigNumberish;
    directionalExposure: BigNumberish;
    stressedLoss: BigNumberish;
    stressedCollateral: BigNumberish;
    stressedLiquidity: BigNumberish;
    requiredCapital: BigNumberish;
    availableCapital: BigNumberish;
    surplus: BigNumberish;
    shortfall: BigNumberish;
    coverageBps: BigNumberish;
    openInterestUtilizationBps: BigNumberish;
    concentrationBps: BigNumberish;
    signals: BigNumberish;
    band: BigNumberish;
  };

  export type MarketAssessmentStructOutput = [
    marketId: string,
    grossOpenInterest: bigint,
    directionalExposure: bigint,
    stressedLoss: bigint,
    stressedCollateral: bigint,
    stressedLiquidity: bigint,
    requiredCapital: bigint,
    availableCapital: bigint,
    surplus: bigint,
    shortfall: bigint,
    coverageBps: bigint,
    openInterestUtilizationBps: bigint,
    concentrationBps: bigint,
    signals: bigint,
    band: bigint
  ] & {
    marketId: string;
    grossOpenInterest: bigint;
    directionalExposure: bigint;
    stressedLoss: bigint;
    stressedCollateral: bigint;
    stressedLiquidity: bigint;
    requiredCapital: bigint;
    availableCapital: bigint;
    surplus: bigint;
    shortfall: bigint;
    coverageBps: bigint;
    openInterestUtilizationBps: bigint;
    concentrationBps: bigint;
    signals: bigint;
    band: bigint;
  };

  export type PortfolioAssessmentStruct = {
    markets: CapitalStressEngine.MarketAssessmentStruct[];
    totalRequiredCapital: BigNumberish;
    totalAvailableCapital: BigNumberish;
    totalSurplus: BigNumberish;
    totalShortfall: BigNumberish;
    aggregateCoverageBps: BigNumberish;
    marketsAtRisk: BigNumberish;
    aggregateSignals: BigNumberish;
    worstBand: BigNumberish;
  };

  export type PortfolioAssessmentStructOutput = [
    markets: CapitalStressEngine.MarketAssessmentStructOutput[],
    totalRequiredCapital: bigint,
    totalAvailableCapital: bigint,
    totalSurplus: bigint,
    totalShortfall: bigint,
    aggregateCoverageBps: bigint,
    marketsAtRisk: bigint,
    aggregateSignals: bigint,
    worstBand: bigint
  ] & {
    markets: CapitalStressEngine.MarketAssessmentStructOutput[];
    totalRequiredCapital: bigint;
    totalAvailableCapital: bigint;
    totalSurplus: bigint;
    totalShortfall: bigint;
    aggregateCoverageBps: bigint;
    marketsAtRisk: bigint;
    aggregateSignals: bigint;
    worstBand: bigint;
  };
}

export interface CapitalStressEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "MAX_COVERAGE_BPS"
      | "SIGNAL_CONCENTRATION"
      | "SIGNAL_LIQUIDITY"
      | "SIGNAL_OPEN_INTEREST"
      | "SIGNAL_ORACLE_CONFIDENCE"
      | "SIGNAL_SHORTFALL"
      | "assessMarket"
      | "assessPortfolio"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_COVERAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_CONCENTRATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_OPEN_INTEREST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_ORACLE_CONFIDENCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_SHORTFALL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assessMarket",
    values: [
      CapitalStressEngine.MarketExposureStruct,
      CapitalStressEngine.StressPolicyStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "assessPortfolio",
    values: [
      CapitalStressEngine.MarketExposureStruct[],
      CapitalStressEngine.StressPolicyStruct
    ]
  ): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COVERAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_CONCENTRATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_OPEN_INTEREST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_ORACLE_CONFIDENCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_SHORTFALL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assessMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assessPortfolio",
    data: BytesLike
  ): Result;
}

export interface CapitalStressEngine extends BaseContract {
  connect(runner?: ContractRunner | null): CapitalStressEngine;
  waitForDeployment(): Promise<this>;

  interface: CapitalStressEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_COVERAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  SIGNAL_CONCENTRATION: TypedContractMethod<[], [bigint], "view">;

  SIGNAL_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  SIGNAL_OPEN_INTEREST: TypedContractMethod<[], [bigint], "view">;

  SIGNAL_ORACLE_CONFIDENCE: TypedContractMethod<[], [bigint], "view">;

  SIGNAL_SHORTFALL: TypedContractMethod<[], [bigint], "view">;

  assessMarket: TypedContractMethod<
    [
      exposure: CapitalStressEngine.MarketExposureStruct,
      policy: CapitalStressEngine.StressPolicyStruct
    ],
    [CapitalStressEngine.MarketAssessmentStructOutput],
    "view"
  >;

  assessPortfolio: TypedContractMethod<
    [
      exposures: CapitalStressEngine.MarketExposureStruct[],
      policy: CapitalStressEngine.StressPolicyStruct
    ],
    [CapitalStressEngine.PortfolioAssessmentStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_COVERAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_CONCENTRATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_OPEN_INTEREST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_ORACLE_CONFIDENCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_SHORTFALL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assessMarket"
  ): TypedContractMethod<
    [
      exposure: CapitalStressEngine.MarketExposureStruct,
      policy: CapitalStressEngine.StressPolicyStruct
    ],
    [CapitalStressEngine.MarketAssessmentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "assessPortfolio"
  ): TypedContractMethod<
    [
      exposures: CapitalStressEngine.MarketExposureStruct[],
      policy: CapitalStressEngine.StressPolicyStruct
    ],
    [CapitalStressEngine.PortfolioAssessmentStructOutput],
    "view"
  >;

  filters: {};
}
