/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AccountTypes {
  export type AccountSnapshotStruct = {
    collateralValue: BigNumberish;
    weightedCollateralValue: BigNumberish;
    debtValue: BigNumberish;
    unrealizedPnl: BigNumberish;
    initialRequirement: BigNumberish;
    maintenanceRequirement: BigNumberish;
    marginRatioBps: BigNumberish;
    healthy: boolean;
    liquidatable: boolean;
  };

  export type AccountSnapshotStructOutput = [
    collateralValue: bigint,
    weightedCollateralValue: bigint,
    debtValue: bigint,
    unrealizedPnl: bigint,
    initialRequirement: bigint,
    maintenanceRequirement: bigint,
    marginRatioBps: bigint,
    healthy: boolean,
    liquidatable: boolean
  ] & {
    collateralValue: bigint;
    weightedCollateralValue: bigint;
    debtValue: bigint;
    unrealizedPnl: bigint;
    initialRequirement: bigint;
    maintenanceRequirement: bigint;
    marginRatioBps: bigint;
    healthy: boolean;
    liquidatable: boolean;
  };
}

export declare namespace EquinoxLens {
  export type CollateralLineStruct = {
    asset: BytesLike;
    balance: BigNumberish;
    value: BigNumberish;
  };

  export type CollateralLineStructOutput = [
    asset: string,
    balance: bigint,
    value: bigint
  ] & { asset: string; balance: bigint; value: bigint };

  export type DebtLineStruct = {
    asset: BytesLike;
    principal: BigNumberish;
    index: BigNumberish;
    currentDebt: BigNumberish;
    value: BigNumberish;
  };

  export type DebtLineStructOutput = [
    asset: string,
    principal: bigint,
    index: bigint,
    currentDebt: bigint,
    value: bigint
  ] & {
    asset: string;
    principal: bigint;
    index: bigint;
    currentDebt: bigint;
    value: bigint;
  };

  export type PositionLineStruct = {
    marketId: BytesLike;
    size: BigNumberish;
    entryPrice: BigNumberish;
    openNotional: BigNumberish;
    unrealizedPnl: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type PositionLineStructOutput = [
    marketId: string,
    size: bigint,
    entryPrice: bigint,
    openNotional: bigint,
    unrealizedPnl: bigint,
    updatedAt: bigint
  ] & {
    marketId: string;
    size: bigint;
    entryPrice: bigint;
    openNotional: bigint;
    unrealizedPnl: bigint;
    updatedAt: bigint;
  };

  export type AccountViewStruct = {
    owner: AddressLike;
    subAccountId: BigNumberish;
    snapshot: AccountTypes.AccountSnapshotStruct;
    collateral: EquinoxLens.CollateralLineStruct[];
    debt: EquinoxLens.DebtLineStruct[];
    positions: EquinoxLens.PositionLineStruct[];
  };

  export type AccountViewStructOutput = [
    owner: string,
    subAccountId: bigint,
    snapshot: AccountTypes.AccountSnapshotStructOutput,
    collateral: EquinoxLens.CollateralLineStructOutput[],
    debt: EquinoxLens.DebtLineStructOutput[],
    positions: EquinoxLens.PositionLineStructOutput[]
  ] & {
    owner: string;
    subAccountId: bigint;
    snapshot: AccountTypes.AccountSnapshotStructOutput;
    collateral: EquinoxLens.CollateralLineStructOutput[];
    debt: EquinoxLens.DebtLineStructOutput[];
    positions: EquinoxLens.PositionLineStructOutput[];
  };

  export type AssetViewStruct = {
    asset: BytesLike;
    token: AddressLike;
    decimals: BigNumberish;
    price: BigNumberish;
    collateralFactorBps: BigNumberish;
    liquidationThresholdBps: BigNumberish;
    liquidationBonusBps: BigNumberish;
    collateralEnabled: boolean;
    borrowEnabled: boolean;
  };

  export type AssetViewStructOutput = [
    asset: string,
    token: string,
    decimals: bigint,
    price: bigint,
    collateralFactorBps: bigint,
    liquidationThresholdBps: bigint,
    liquidationBonusBps: bigint,
    collateralEnabled: boolean,
    borrowEnabled: boolean
  ] & {
    asset: string;
    token: string;
    decimals: bigint;
    price: bigint;
    collateralFactorBps: bigint;
    liquidationThresholdBps: bigint;
    liquidationBonusBps: bigint;
    collateralEnabled: boolean;
    borrowEnabled: boolean;
  };

  export type PoolViewStruct = {
    asset: BytesLike;
    cash: BigNumberish;
    totalShares: BigNumberish;
    totalBorrowDebt: BigNumberish;
    borrowIndex: BigNumberish;
    reserveBalance: BigNumberish;
    utilization: BigNumberish;
    netAssets: BigNumberish;
  };

  export type PoolViewStructOutput = [
    asset: string,
    cash: bigint,
    totalShares: bigint,
    totalBorrowDebt: bigint,
    borrowIndex: bigint,
    reserveBalance: bigint,
    utilization: bigint,
    netAssets: bigint
  ] & {
    asset: string;
    cash: bigint;
    totalShares: bigint;
    totalBorrowDebt: bigint;
    borrowIndex: bigint;
    reserveBalance: bigint;
    utilization: bigint;
    netAssets: bigint;
  };

  export type MarketViewStruct = {
    marketId: BytesLike;
    baseAsset: BytesLike;
    quoteAsset: BytesLike;
    maxLeverageBps: BigNumberish;
    maintenanceMarginBps: BigNumberish;
    takerFeeBps: BigNumberish;
    liquidationCloseFactorBps: BigNumberish;
    reduceOnly: boolean;
    active: boolean;
    base: EquinoxLens.AssetViewStruct;
    quote: EquinoxLens.AssetViewStruct;
    quotePool: EquinoxLens.PoolViewStruct;
  };

  export type MarketViewStructOutput = [
    marketId: string,
    baseAsset: string,
    quoteAsset: string,
    maxLeverageBps: bigint,
    maintenanceMarginBps: bigint,
    takerFeeBps: bigint,
    liquidationCloseFactorBps: bigint,
    reduceOnly: boolean,
    active: boolean,
    base: EquinoxLens.AssetViewStructOutput,
    quote: EquinoxLens.AssetViewStructOutput,
    quotePool: EquinoxLens.PoolViewStructOutput
  ] & {
    marketId: string;
    baseAsset: string;
    quoteAsset: string;
    maxLeverageBps: bigint;
    maintenanceMarginBps: bigint;
    takerFeeBps: bigint;
    liquidationCloseFactorBps: bigint;
    reduceOnly: boolean;
    active: boolean;
    base: EquinoxLens.AssetViewStructOutput;
    quote: EquinoxLens.AssetViewStructOutput;
    quotePool: EquinoxLens.PoolViewStructOutput;
  };
}

export interface EquinoxLensInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountView"
      | "assetView"
      | "marketView"
      | "poolView"
      | "portfolioHealth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountView",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetView",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketView",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolView",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "portfolioHealth",
    values: [AddressLike, AddressLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetView", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "marketView", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolView", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "portfolioHealth",
    data: BytesLike
  ): Result;
}

export interface EquinoxLens extends BaseContract {
  connect(runner?: ContractRunner | null): EquinoxLens;
  waitForDeployment(): Promise<this>;

  interface: EquinoxLensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountView: TypedContractMethod<
    [protocol: AddressLike, owner: AddressLike, subAccountId: BigNumberish],
    [EquinoxLens.AccountViewStructOutput],
    "view"
  >;

  assetView: TypedContractMethod<
    [protocol: AddressLike, asset: BytesLike],
    [EquinoxLens.AssetViewStructOutput],
    "view"
  >;

  marketView: TypedContractMethod<
    [protocol: AddressLike, marketId: BytesLike],
    [EquinoxLens.MarketViewStructOutput],
    "view"
  >;

  poolView: TypedContractMethod<
    [protocol: AddressLike, asset: BytesLike],
    [EquinoxLens.PoolViewStructOutput],
    "view"
  >;

  portfolioHealth: TypedContractMethod<
    [protocol: AddressLike, owner: AddressLike, subAccountIds: BigNumberish[]],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        collateralValue: bigint;
        weightedCollateralValue: bigint;
        debtValue: bigint;
        pnlValue: bigint;
        initialRequirement: bigint;
        maintenanceRequirement: bigint;
        allHealthy: boolean;
        anyLiquidatable: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountView"
  ): TypedContractMethod<
    [protocol: AddressLike, owner: AddressLike, subAccountId: BigNumberish],
    [EquinoxLens.AccountViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "assetView"
  ): TypedContractMethod<
    [protocol: AddressLike, asset: BytesLike],
    [EquinoxLens.AssetViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketView"
  ): TypedContractMethod<
    [protocol: AddressLike, marketId: BytesLike],
    [EquinoxLens.MarketViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolView"
  ): TypedContractMethod<
    [protocol: AddressLike, asset: BytesLike],
    [EquinoxLens.PoolViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "portfolioHealth"
  ): TypedContractMethod<
    [protocol: AddressLike, owner: AddressLike, subAccountIds: BigNumberish[]],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        collateralValue: bigint;
        weightedCollateralValue: bigint;
        debtValue: bigint;
        pnlValue: bigint;
        initialRequirement: bigint;
        maintenanceRequirement: bigint;
        allHealthy: boolean;
        anyLiquidatable: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
