/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SettlementQueue {
  export type SettlementTicketStruct = {
    id: BytesLike;
    accountOwner: AddressLike;
    subAccountId: BigNumberish;
    marketId: BytesLike;
    asset: BytesLike;
    sizeDelta: BigNumberish;
    notionalValue: BigNumberish;
    collateralValue: BigNumberish;
    debtValue: BigNumberish;
    validAfter: BigNumberish;
    expiresAt: BigNumberish;
    createdAt: BigNumberish;
    status: BigNumberish;
  };

  export type SettlementTicketStructOutput = [
    id: string,
    accountOwner: string,
    subAccountId: bigint,
    marketId: string,
    asset: string,
    sizeDelta: bigint,
    notionalValue: bigint,
    collateralValue: bigint,
    debtValue: bigint,
    validAfter: bigint,
    expiresAt: bigint,
    createdAt: bigint,
    status: bigint
  ] & {
    id: string;
    accountOwner: string;
    subAccountId: bigint;
    marketId: string;
    asset: string;
    sizeDelta: bigint;
    notionalValue: bigint;
    collateralValue: bigint;
    debtValue: bigint;
    validAfter: bigint;
    expiresAt: bigint;
    createdAt: bigint;
    status: bigint;
  };

  export type QueueStatsStruct = {
    pending: BigNumberish;
    ready: BigNumberish;
    consumed: BigNumberish;
    cancelled: BigNumberish;
    expired: BigNumberish;
  };

  export type QueueStatsStructOutput = [
    pending: bigint,
    ready: bigint,
    consumed: bigint,
    cancelled: bigint,
    expired: bigint
  ] & {
    pending: bigint;
    ready: bigint;
    consumed: bigint;
    cancelled: bigint;
    expired: bigint;
  };
}

export interface SettlementQueueInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancel"
      | "configureTiming"
      | "consume"
      | "coordinator"
      | "createTicket"
      | "executableTickets"
      | "expire"
      | "getTicket"
      | "isExecutable"
      | "markReady"
      | "maxTtl"
      | "minDelay"
      | "nextSequence"
      | "ownerTickets"
      | "pendingTickets"
      | "queueStats"
      | "ticketIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "QueueTimingUpdated"
      | "TicketCancelled"
      | "TicketConsumed"
      | "TicketCreated"
      | "TicketReady"
  ): EventFragment;

  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "configureTiming",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "consume", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "coordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTicket",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executableTickets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "expire", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTicket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "maxTtl", values?: undefined): string;
  encodeFunctionData(functionFragment: "minDelay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextSequence",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerTickets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTickets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueStats",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ticketIds", values?: undefined): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "configureTiming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consume", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executableTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "expire", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isExecutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markReady", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxTtl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minDelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextSequence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "queueStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ticketIds", data: BytesLike): Result;
}

export namespace QueueTimingUpdatedEvent {
  export type InputTuple = [minDelay: BigNumberish, maxTtl: BigNumberish];
  export type OutputTuple = [minDelay: bigint, maxTtl: bigint];
  export interface OutputObject {
    minDelay: bigint;
    maxTtl: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketCancelledEvent {
  export type InputTuple = [ticketId: BytesLike, caller: AddressLike];
  export type OutputTuple = [ticketId: string, caller: string];
  export interface OutputObject {
    ticketId: string;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketConsumedEvent {
  export type InputTuple = [ticketId: BytesLike, executor: AddressLike];
  export type OutputTuple = [ticketId: string, executor: string];
  export interface OutputObject {
    ticketId: string;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketCreatedEvent {
  export type InputTuple = [
    ticketId: BytesLike,
    accountOwner: AddressLike,
    subAccountId: BigNumberish,
    marketId: BytesLike,
    notionalValue: BigNumberish,
    validAfter: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: string,
    accountOwner: string,
    subAccountId: bigint,
    marketId: string,
    notionalValue: bigint,
    validAfter: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    ticketId: string;
    accountOwner: string;
    subAccountId: bigint;
    marketId: string;
    notionalValue: bigint;
    validAfter: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketReadyEvent {
  export type InputTuple = [ticketId: BytesLike];
  export type OutputTuple = [ticketId: string];
  export interface OutputObject {
    ticketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementQueue extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementQueue;
  waitForDeployment(): Promise<this>;

  interface: SettlementQueueInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancel: TypedContractMethod<[ticketId: BytesLike], [void], "nonpayable">;

  configureTiming: TypedContractMethod<
    [minDelay_: BigNumberish, maxTtl_: BigNumberish],
    [void],
    "nonpayable"
  >;

  consume: TypedContractMethod<
    [ticketId: BytesLike],
    [SettlementQueue.SettlementTicketStructOutput],
    "nonpayable"
  >;

  coordinator: TypedContractMethod<[], [string], "view">;

  createTicket: TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike,
      asset: BytesLike,
      sizeDelta: BigNumberish,
      notionalValue: BigNumberish,
      collateralValue: BigNumberish,
      debtValue: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  executableTickets: TypedContractMethod<
    [accountOwner: AddressLike],
    [string[]],
    "view"
  >;

  expire: TypedContractMethod<[ticketId: BytesLike], [void], "nonpayable">;

  getTicket: TypedContractMethod<
    [ticketId: BytesLike],
    [SettlementQueue.SettlementTicketStructOutput],
    "view"
  >;

  isExecutable: TypedContractMethod<[ticketId: BytesLike], [boolean], "view">;

  markReady: TypedContractMethod<[ticketId: BytesLike], [void], "nonpayable">;

  maxTtl: TypedContractMethod<[], [bigint], "view">;

  minDelay: TypedContractMethod<[], [bigint], "view">;

  nextSequence: TypedContractMethod<[], [bigint], "view">;

  ownerTickets: TypedContractMethod<
    [accountOwner: AddressLike],
    [string[]],
    "view"
  >;

  pendingTickets: TypedContractMethod<
    [accountOwner: AddressLike],
    [string[]],
    "view"
  >;

  queueStats: TypedContractMethod<
    [],
    [SettlementQueue.QueueStatsStructOutput],
    "view"
  >;

  ticketIds: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[ticketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configureTiming"
  ): TypedContractMethod<
    [minDelay_: BigNumberish, maxTtl_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "consume"
  ): TypedContractMethod<
    [ticketId: BytesLike],
    [SettlementQueue.SettlementTicketStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "coordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createTicket"
  ): TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike,
      asset: BytesLike,
      sizeDelta: BigNumberish,
      notionalValue: BigNumberish,
      collateralValue: BigNumberish,
      debtValue: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executableTickets"
  ): TypedContractMethod<[accountOwner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "expire"
  ): TypedContractMethod<[ticketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTicket"
  ): TypedContractMethod<
    [ticketId: BytesLike],
    [SettlementQueue.SettlementTicketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExecutable"
  ): TypedContractMethod<[ticketId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markReady"
  ): TypedContractMethod<[ticketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "maxTtl"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextSequence"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ownerTickets"
  ): TypedContractMethod<[accountOwner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "pendingTickets"
  ): TypedContractMethod<[accountOwner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "queueStats"
  ): TypedContractMethod<[], [SettlementQueue.QueueStatsStructOutput], "view">;
  getFunction(
    nameOrSignature: "ticketIds"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "QueueTimingUpdated"
  ): TypedContractEvent<
    QueueTimingUpdatedEvent.InputTuple,
    QueueTimingUpdatedEvent.OutputTuple,
    QueueTimingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TicketCancelled"
  ): TypedContractEvent<
    TicketCancelledEvent.InputTuple,
    TicketCancelledEvent.OutputTuple,
    TicketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TicketConsumed"
  ): TypedContractEvent<
    TicketConsumedEvent.InputTuple,
    TicketConsumedEvent.OutputTuple,
    TicketConsumedEvent.OutputObject
  >;
  getEvent(
    key: "TicketCreated"
  ): TypedContractEvent<
    TicketCreatedEvent.InputTuple,
    TicketCreatedEvent.OutputTuple,
    TicketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TicketReady"
  ): TypedContractEvent<
    TicketReadyEvent.InputTuple,
    TicketReadyEvent.OutputTuple,
    TicketReadyEvent.OutputObject
  >;

  filters: {
    "QueueTimingUpdated(uint256,uint256)": TypedContractEvent<
      QueueTimingUpdatedEvent.InputTuple,
      QueueTimingUpdatedEvent.OutputTuple,
      QueueTimingUpdatedEvent.OutputObject
    >;
    QueueTimingUpdated: TypedContractEvent<
      QueueTimingUpdatedEvent.InputTuple,
      QueueTimingUpdatedEvent.OutputTuple,
      QueueTimingUpdatedEvent.OutputObject
    >;

    "TicketCancelled(bytes32,address)": TypedContractEvent<
      TicketCancelledEvent.InputTuple,
      TicketCancelledEvent.OutputTuple,
      TicketCancelledEvent.OutputObject
    >;
    TicketCancelled: TypedContractEvent<
      TicketCancelledEvent.InputTuple,
      TicketCancelledEvent.OutputTuple,
      TicketCancelledEvent.OutputObject
    >;

    "TicketConsumed(bytes32,address)": TypedContractEvent<
      TicketConsumedEvent.InputTuple,
      TicketConsumedEvent.OutputTuple,
      TicketConsumedEvent.OutputObject
    >;
    TicketConsumed: TypedContractEvent<
      TicketConsumedEvent.InputTuple,
      TicketConsumedEvent.OutputTuple,
      TicketConsumedEvent.OutputObject
    >;

    "TicketCreated(bytes32,address,uint256,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      TicketCreatedEvent.InputTuple,
      TicketCreatedEvent.OutputTuple,
      TicketCreatedEvent.OutputObject
    >;
    TicketCreated: TypedContractEvent<
      TicketCreatedEvent.InputTuple,
      TicketCreatedEvent.OutputTuple,
      TicketCreatedEvent.OutputObject
    >;

    "TicketReady(bytes32)": TypedContractEvent<
      TicketReadyEvent.InputTuple,
      TicketReadyEvent.OutputTuple,
      TicketReadyEvent.OutputObject
    >;
    TicketReady: TypedContractEvent<
      TicketReadyEvent.InputTuple,
      TicketReadyEvent.OutputTuple,
      TicketReadyEvent.OutputObject
    >;
  };
}
