/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ExecutionCodec,
  ExecutionCodecInterface,
} from "../../core/ExecutionCodec";

const _abi = [
  {
    inputs: [],
    name: "ExpiredIntent",
    type: "error",
  },
  {
    inputs: [],
    name: "FeeExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidFill",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidPrice",
    type: "error",
  },
  {
    inputs: [],
    name: "ReduceOnlyViolation",
    type: "error",
  },
  {
    inputs: [],
    name: "SlippageExceeded",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220e58465bd231fa7cafb746f13294bc1dbd0cf7ce35cc7a2648d4dcb5c904ffbc264736f6c63430008180033";

type ExecutionCodecConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExecutionCodecConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExecutionCodec__factory extends ContractFactory {
  constructor(...args: ExecutionCodecConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ExecutionCodec & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ExecutionCodec__factory {
    return super.connect(runner) as ExecutionCodec__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExecutionCodecInterface {
    return new Interface(_abi) as ExecutionCodecInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ExecutionCodec {
    return new Contract(address, _abi, runner) as unknown as ExecutionCodec;
  }
}
