/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IEquinoxOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "getPrice" | "getPriceUnsafe" | "isFresh"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PricePosted"
      | "PublisherUpdated"
      | "StalenessUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getPrice", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPriceUnsafe",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isFresh", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceUnsafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFresh", data: BytesLike): Result;
}

export namespace PricePostedEvent {
  export type InputTuple = [
    asset: BytesLike,
    price: BigNumberish,
    timestamp: BigNumberish,
    publisher: AddressLike
  ];
  export type OutputTuple = [
    asset: string,
    price: bigint,
    timestamp: bigint,
    publisher: string
  ];
  export interface OutputObject {
    asset: string;
    price: bigint;
    timestamp: bigint;
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublisherUpdatedEvent {
  export type InputTuple = [publisher: AddressLike, enabled: boolean];
  export type OutputTuple = [publisher: string, enabled: boolean];
  export interface OutputObject {
    publisher: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StalenessUpdatedEvent {
  export type InputTuple = [maxDelay: BigNumberish];
  export type OutputTuple = [maxDelay: bigint];
  export interface OutputObject {
    maxDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEquinoxOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IEquinoxOracle;
  waitForDeployment(): Promise<this>;

  interface: IEquinoxOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPrice: TypedContractMethod<[asset: BytesLike], [bigint], "view">;

  getPriceUnsafe: TypedContractMethod<
    [asset: BytesLike],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;

  isFresh: TypedContractMethod<[asset: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[asset: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPriceUnsafe"
  ): TypedContractMethod<
    [asset: BytesLike],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFresh"
  ): TypedContractMethod<[asset: BytesLike], [boolean], "view">;

  getEvent(
    key: "PricePosted"
  ): TypedContractEvent<
    PricePostedEvent.InputTuple,
    PricePostedEvent.OutputTuple,
    PricePostedEvent.OutputObject
  >;
  getEvent(
    key: "PublisherUpdated"
  ): TypedContractEvent<
    PublisherUpdatedEvent.InputTuple,
    PublisherUpdatedEvent.OutputTuple,
    PublisherUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StalenessUpdated"
  ): TypedContractEvent<
    StalenessUpdatedEvent.InputTuple,
    StalenessUpdatedEvent.OutputTuple,
    StalenessUpdatedEvent.OutputObject
  >;

  filters: {
    "PricePosted(bytes32,uint256,uint256,address)": TypedContractEvent<
      PricePostedEvent.InputTuple,
      PricePostedEvent.OutputTuple,
      PricePostedEvent.OutputObject
    >;
    PricePosted: TypedContractEvent<
      PricePostedEvent.InputTuple,
      PricePostedEvent.OutputTuple,
      PricePostedEvent.OutputObject
    >;

    "PublisherUpdated(address,bool)": TypedContractEvent<
      PublisherUpdatedEvent.InputTuple,
      PublisherUpdatedEvent.OutputTuple,
      PublisherUpdatedEvent.OutputObject
    >;
    PublisherUpdated: TypedContractEvent<
      PublisherUpdatedEvent.InputTuple,
      PublisherUpdatedEvent.OutputTuple,
      PublisherUpdatedEvent.OutputObject
    >;

    "StalenessUpdated(uint256)": TypedContractEvent<
      StalenessUpdatedEvent.InputTuple,
      StalenessUpdatedEvent.OutputTuple,
      StalenessUpdatedEvent.OutputObject
    >;
    StalenessUpdated: TypedContractEvent<
      StalenessUpdatedEvent.InputTuple,
      StalenessUpdatedEvent.OutputTuple,
      StalenessUpdatedEvent.OutputObject
    >;
  };
}
