/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AccountTypes {
  export type AccountSnapshotStruct = {
    collateralValue: BigNumberish;
    weightedCollateralValue: BigNumberish;
    debtValue: BigNumberish;
    unrealizedPnl: BigNumberish;
    initialRequirement: BigNumberish;
    maintenanceRequirement: BigNumberish;
    marginRatioBps: BigNumberish;
    healthy: boolean;
    liquidatable: boolean;
  };

  export type AccountSnapshotStructOutput = [
    collateralValue: bigint,
    weightedCollateralValue: bigint,
    debtValue: bigint,
    unrealizedPnl: bigint,
    initialRequirement: bigint,
    maintenanceRequirement: bigint,
    marginRatioBps: bigint,
    healthy: boolean,
    liquidatable: boolean
  ] & {
    collateralValue: bigint;
    weightedCollateralValue: bigint;
    debtValue: bigint;
    unrealizedPnl: bigint;
    initialRequirement: bigint;
    maintenanceRequirement: bigint;
    marginRatioBps: bigint;
    healthy: boolean;
    liquidatable: boolean;
  };

  export type AssetConfigStruct = {
    id: BytesLike;
    token: AddressLike;
    decimals: BigNumberish;
    collateralFactorBps: BigNumberish;
    liquidationThresholdBps: BigNumberish;
    liquidationBonusBps: BigNumberish;
    collateralEnabled: boolean;
    borrowEnabled: boolean;
    registered: boolean;
  };

  export type AssetConfigStructOutput = [
    id: string,
    token: string,
    decimals: bigint,
    collateralFactorBps: bigint,
    liquidationThresholdBps: bigint,
    liquidationBonusBps: bigint,
    collateralEnabled: boolean,
    borrowEnabled: boolean,
    registered: boolean
  ] & {
    id: string;
    token: string;
    decimals: bigint;
    collateralFactorBps: bigint;
    liquidationThresholdBps: bigint;
    liquidationBonusBps: bigint;
    collateralEnabled: boolean;
    borrowEnabled: boolean;
    registered: boolean;
  };

  export type MarketConfigStruct = {
    id: BytesLike;
    baseAsset: BytesLike;
    quoteAsset: BytesLike;
    maxLeverageBps: BigNumberish;
    maintenanceMarginBps: BigNumberish;
    takerFeeBps: BigNumberish;
    liquidationCloseFactorBps: BigNumberish;
    reduceOnly: boolean;
    active: boolean;
    registered: boolean;
  };

  export type MarketConfigStructOutput = [
    id: string,
    baseAsset: string,
    quoteAsset: string,
    maxLeverageBps: bigint,
    maintenanceMarginBps: bigint,
    takerFeeBps: bigint,
    liquidationCloseFactorBps: bigint,
    reduceOnly: boolean,
    active: boolean,
    registered: boolean
  ] & {
    id: string;
    baseAsset: string;
    quoteAsset: string;
    maxLeverageBps: bigint;
    maintenanceMarginBps: bigint;
    takerFeeBps: bigint;
    liquidationCloseFactorBps: bigint;
    reduceOnly: boolean;
    active: boolean;
    registered: boolean;
  };

  export type LiquidationQuoteStruct = {
    marketId: BytesLike;
    debtAsset: BytesLike;
    seizeAsset: BytesLike;
    repayAmount: BigNumberish;
    repayPrincipal: BigNumberish;
    seizeAmount: BigNumberish;
    closeNotional: BigNumberish;
    bonusValue: BigNumberish;
    healthBeforeBps: BigNumberish;
  };

  export type LiquidationQuoteStructOutput = [
    marketId: string,
    debtAsset: string,
    seizeAsset: string,
    repayAmount: bigint,
    repayPrincipal: bigint,
    seizeAmount: bigint,
    closeNotional: bigint,
    bonusValue: bigint,
    healthBeforeBps: bigint
  ] & {
    marketId: string;
    debtAsset: string;
    seizeAsset: string;
    repayAmount: bigint;
    repayPrincipal: bigint;
    seizeAmount: bigint;
    closeNotional: bigint;
    bonusValue: bigint;
    healthBeforeBps: bigint;
  };

  export type TransferReceiptStruct = {
    owner: AddressLike;
    sourceSubAccount: BigNumberish;
    targetSubAccount: BigNumberish;
    marketId: BytesLike;
    positionPortionBps: BigNumberish;
    principalMoved: BigNumberish;
    collateralMovedValue: BigNumberish;
    issuedAt: BigNumberish;
  };

  export type TransferReceiptStructOutput = [
    owner: string,
    sourceSubAccount: bigint,
    targetSubAccount: bigint,
    marketId: string,
    positionPortionBps: bigint,
    principalMoved: bigint,
    collateralMovedValue: bigint,
    issuedAt: bigint
  ] & {
    owner: string;
    sourceSubAccount: bigint;
    targetSubAccount: bigint;
    marketId: string;
    positionPortionBps: bigint;
    principalMoved: bigint;
    collateralMovedValue: bigint;
    issuedAt: bigint;
  };
}

export interface EquinoxMarginProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_COLLATERAL_FACTOR_BPS"
      | "MAX_LEVERAGE_BPS"
      | "MAX_LIQUIDATION_BONUS_BPS"
      | "MIN_COLLATERAL_FACTOR_BPS"
      | "MIN_LEVERAGE_BPS"
      | "accountSnapshot"
      | "accrueInterest"
      | "addMargin"
      | "assetConfig"
      | "closePosition"
      | "collateralAssets"
      | "collateralBalance"
      | "collectReserves"
      | "configureAssetRisk"
      | "configureInterestRate"
      | "debtAssets"
      | "debtOf"
      | "depositLiquidity"
      | "depositMargin"
      | "getAssets"
      | "getMarkets"
      | "liquidate"
      | "liquidityShares"
      | "marketConfig"
      | "openPosition"
      | "oracle"
      | "owner"
      | "paused"
      | "poolState"
      | "positionMarkets"
      | "positionOf"
      | "previewLiquidityWithdrawal"
      | "quoteLiquidation"
      | "registerAsset"
      | "registerMarket"
      | "repayDebt"
      | "setMarketMode"
      | "setOracle"
      | "setPaused"
      | "transferOwnership"
      | "transferPosition"
      | "transferSequence"
      | "withdrawLiquidity"
      | "withdrawMargin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRegistered"
      | "AssetRiskUpdated"
      | "DebtIncreased"
      | "DebtRepaid"
      | "InterestAccrued"
      | "InterestRateUpdated"
      | "Liquidated"
      | "LiquidityDeposited"
      | "LiquidityWithdrawn"
      | "MarginDeposited"
      | "MarginWithdrawn"
      | "MarketRegistered"
      | "MarketUpdated"
      | "OracleUpdated"
      | "OwnershipTransferred"
      | "PauseUpdated"
      | "PositionClosed"
      | "PositionOpened"
      | "PositionTransferred"
      | "ReserveCollected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_COLLATERAL_FACTOR_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LEVERAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LIQUIDATION_BONUS_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_FACTOR_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LEVERAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountSnapshot",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "accrueInterest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addMargin",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralAssets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralBalance",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectReserves",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configureAssetRisk",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "configureInterestRate",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "debtAssets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debtOf",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositMargin",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAssets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityShares",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openPosition",
    values: [
      BigNumberish,
      BytesLike,
      boolean,
      BigNumberish,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "positionMarkets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "positionOf",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "previewLiquidityWithdrawal",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteLiquidation",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMarket",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "repayDebt",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketMode",
    values: [BytesLike, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferPosition",
    values: [BigNumberish, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSequence",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMargin",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_COLLATERAL_FACTOR_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LEVERAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LIQUIDATION_BONUS_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_FACTOR_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LEVERAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accrueInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMargin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureAssetRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debtAssets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "debtOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAssets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMarkets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidityShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positionOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewLiquidityWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMarketMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSequence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMargin",
    data: BytesLike
  ): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    asset: BytesLike,
    token: AddressLike,
    decimals: BigNumberish
  ];
  export type OutputTuple = [asset: string, token: string, decimals: bigint];
  export interface OutputObject {
    asset: string;
    token: string;
    decimals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRiskUpdatedEvent {
  export type InputTuple = [
    asset: BytesLike,
    collateralFactorBps: BigNumberish,
    liquidationThresholdBps: BigNumberish,
    liquidationBonusBps: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    collateralFactorBps: bigint,
    liquidationThresholdBps: bigint,
    liquidationBonusBps: bigint
  ];
  export interface OutputObject {
    asset: string;
    collateralFactorBps: bigint;
    liquidationThresholdBps: bigint;
    liquidationBonusBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebtIncreasedEvent {
  export type InputTuple = [
    owner: AddressLike,
    subAccountId: BigNumberish,
    asset: BytesLike,
    amount: BigNumberish,
    index: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    subAccountId: bigint,
    asset: string,
    amount: bigint,
    index: bigint
  ];
  export interface OutputObject {
    owner: string;
    subAccountId: bigint;
    asset: string;
    amount: bigint;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebtRepaidEvent {
  export type InputTuple = [
    owner: AddressLike,
    subAccountId: BigNumberish,
    asset: BytesLike,
    amount: BigNumberish,
    remainingDebt: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    subAccountId: bigint,
    asset: string,
    amount: bigint,
    remainingDebt: bigint
  ];
  export interface OutputObject {
    owner: string;
    subAccountId: bigint;
    asset: string;
    amount: bigint;
    remainingDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterestAccruedEvent {
  export type InputTuple = [
    asset: BytesLike,
    indexBefore: BigNumberish,
    indexAfter: BigNumberish,
    interestAccrued: BigNumberish,
    reserveAccrued: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    indexBefore: bigint,
    indexAfter: bigint,
    interestAccrued: bigint,
    reserveAccrued: bigint
  ];
  export interface OutputObject {
    asset: string;
    indexBefore: bigint;
    indexAfter: bigint;
    interestAccrued: bigint;
    reserveAccrued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterestRateUpdatedEvent {
  export type InputTuple = [
    asset: BytesLike,
    baseRatePerSecond: BigNumberish,
    slope1PerSecond: BigNumberish,
    slope2PerSecond: BigNumberish,
    kinkUtilization: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    baseRatePerSecond: bigint,
    slope1PerSecond: bigint,
    slope2PerSecond: bigint,
    kinkUtilization: bigint
  ];
  export interface OutputObject {
    asset: string;
    baseRatePerSecond: bigint;
    slope1PerSecond: bigint;
    slope2PerSecond: bigint;
    kinkUtilization: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidatedEvent {
  export type InputTuple = [
    liquidator: AddressLike,
    accountOwner: AddressLike,
    subAccountId: BigNumberish,
    marketId: BytesLike,
    debtAsset: BytesLike,
    seizeAsset: BytesLike,
    repaidAmount: BigNumberish,
    seizedAmount: BigNumberish
  ];
  export type OutputTuple = [
    liquidator: string,
    accountOwner: string,
    subAccountId: bigint,
    marketId: string,
    debtAsset: string,
    seizeAsset: string,
    repaidAmount: bigint,
    seizedAmount: bigint
  ];
  export interface OutputObject {
    liquidator: string;
    accountOwner: string;
    subAccountId: bigint;
    marketId: string;
    debtAsset: string;
    seizeAsset: string;
    repaidAmount: bigint;
    seizedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityDepositedEvent {
  export type InputTuple = [
    provider: AddressLike,
    asset: BytesLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    asset: string,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    provider: string;
    asset: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWithdrawnEvent {
  export type InputTuple = [
    provider: AddressLike,
    asset: BytesLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    asset: string,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    provider: string;
    asset: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarginDepositedEvent {
  export type InputTuple = [
    owner: AddressLike,
    subAccountId: BigNumberish,
    asset: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    subAccountId: bigint,
    asset: string,
    amount: bigint
  ];
  export interface OutputObject {
    owner: string;
    subAccountId: bigint;
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarginWithdrawnEvent {
  export type InputTuple = [
    owner: AddressLike,
    subAccountId: BigNumberish,
    asset: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    subAccountId: bigint,
    asset: string,
    amount: bigint
  ];
  export interface OutputObject {
    owner: string;
    subAccountId: bigint;
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketRegisteredEvent {
  export type InputTuple = [
    marketId: BytesLike,
    baseAsset: BytesLike,
    quoteAsset: BytesLike
  ];
  export type OutputTuple = [
    marketId: string,
    baseAsset: string,
    quoteAsset: string
  ];
  export interface OutputObject {
    marketId: string;
    baseAsset: string;
    quoteAsset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketUpdatedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    active: boolean,
    reduceOnly: boolean
  ];
  export type OutputTuple = [
    marketId: string,
    active: boolean,
    reduceOnly: boolean
  ];
  export interface OutputObject {
    marketId: string;
    active: boolean;
    reduceOnly: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [
    previousOracle: AddressLike,
    newOracle: AddressLike
  ];
  export type OutputTuple = [previousOracle: string, newOracle: string];
  export interface OutputObject {
    previousOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseUpdatedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionClosedEvent {
  export type InputTuple = [
    owner: AddressLike,
    subAccountId: BigNumberish,
    marketId: BytesLike,
    sizeDelta: BigNumberish,
    notionalValue: BigNumberish,
    pnlValue: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    subAccountId: bigint,
    marketId: string,
    sizeDelta: bigint,
    notionalValue: bigint,
    pnlValue: bigint
  ];
  export interface OutputObject {
    owner: string;
    subAccountId: bigint;
    marketId: string;
    sizeDelta: bigint;
    notionalValue: bigint;
    pnlValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [
    owner: AddressLike,
    subAccountId: BigNumberish,
    marketId: BytesLike,
    sizeDelta: BigNumberish,
    notionalValue: BigNumberish,
    entryPrice: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    subAccountId: bigint,
    marketId: string,
    sizeDelta: bigint,
    notionalValue: bigint,
    entryPrice: bigint
  ];
  export interface OutputObject {
    owner: string;
    subAccountId: bigint;
    marketId: string;
    sizeDelta: bigint;
    notionalValue: bigint;
    entryPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionTransferredEvent {
  export type InputTuple = [
    owner: AddressLike,
    sourceSubAccount: BigNumberish,
    targetSubAccount: BigNumberish,
    marketId: BytesLike,
    portionBps: BigNumberish,
    principalMoved: BigNumberish,
    transferId: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    sourceSubAccount: bigint,
    targetSubAccount: bigint,
    marketId: string,
    portionBps: bigint,
    principalMoved: bigint,
    transferId: bigint
  ];
  export interface OutputObject {
    owner: string;
    sourceSubAccount: bigint;
    targetSubAccount: bigint;
    marketId: string;
    portionBps: bigint;
    principalMoved: bigint;
    transferId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveCollectedEvent {
  export type InputTuple = [
    asset: BytesLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [asset: string, amount: bigint, recipient: string];
  export interface OutputObject {
    asset: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EquinoxMarginProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): EquinoxMarginProtocol;
  waitForDeployment(): Promise<this>;

  interface: EquinoxMarginProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_COLLATERAL_FACTOR_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_LEVERAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_LIQUIDATION_BONUS_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_COLLATERAL_FACTOR_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_LEVERAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  accountSnapshot: TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [AccountTypes.AccountSnapshotStructOutput],
    "view"
  >;

  accrueInterest: TypedContractMethod<
    [asset: BytesLike],
    [bigint],
    "nonpayable"
  >;

  addMargin: TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  assetConfig: TypedContractMethod<
    [asset: BytesLike],
    [AccountTypes.AssetConfigStructOutput],
    "view"
  >;

  closePosition: TypedContractMethod<
    [
      subAccountId: BigNumberish,
      marketId: BytesLike,
      notionalValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  collateralAssets: TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [string[]],
    "view"
  >;

  collateralBalance: TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish, asset: BytesLike],
    [bigint],
    "view"
  >;

  collectReserves: TypedContractMethod<
    [asset: BytesLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  configureAssetRisk: TypedContractMethod<
    [
      asset: BytesLike,
      collateralFactorBps: BigNumberish,
      liquidationThresholdBps: BigNumberish,
      liquidationBonusBps: BigNumberish,
      collateralEnabled: boolean,
      borrowEnabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  configureInterestRate: TypedContractMethod<
    [
      asset: BytesLike,
      baseRatePerSecond: BigNumberish,
      slope1PerSecond: BigNumberish,
      slope2PerSecond: BigNumberish,
      kinkUtilization: BigNumberish,
      reserveFactorBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  debtAssets: TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [string[]],
    "view"
  >;

  debtOf: TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish, asset: BytesLike],
    [
      [bigint, bigint, bigint] & {
        principal: bigint;
        index: bigint;
        currentDebt: bigint;
      }
    ],
    "view"
  >;

  depositLiquidity: TypedContractMethod<
    [asset: BytesLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  depositMargin: TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAssets: TypedContractMethod<[], [string[]], "view">;

  getMarkets: TypedContractMethod<[], [string[]], "view">;

  liquidate: TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike,
      seizeAsset: BytesLike,
      repayAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  liquidityShares: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  marketConfig: TypedContractMethod<
    [marketId: BytesLike],
    [AccountTypes.MarketConfigStructOutput],
    "view"
  >;

  openPosition: TypedContractMethod<
    [
      subAccountId: BigNumberish,
      marketId: BytesLike,
      isLong: boolean,
      notionalValue: BigNumberish,
      collateralAsset: BytesLike,
      collateralAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  poolState: TypedContractMethod<
    [asset: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        cash: bigint;
        totalShares: bigint;
        totalBorrowDebt: bigint;
        borrowIndex: bigint;
        reserveBalance: bigint;
        utilization: bigint;
      }
    ],
    "view"
  >;

  positionMarkets: TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [string[]],
    "view"
  >;

  positionOf: TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike
    ],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        size: bigint;
        entryPrice: bigint;
        openNotional: bigint;
        unrealizedPnl: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  previewLiquidityWithdrawal: TypedContractMethod<
    [asset: BytesLike, shares: BigNumberish],
    [bigint],
    "view"
  >;

  quoteLiquidation: TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike,
      seizeAsset: BytesLike,
      repayAmount: BigNumberish
    ],
    [AccountTypes.LiquidationQuoteStructOutput],
    "view"
  >;

  registerAsset: TypedContractMethod<
    [
      asset: BytesLike,
      token: AddressLike,
      decimals_: BigNumberish,
      collateralFactorBps: BigNumberish,
      liquidationThresholdBps: BigNumberish,
      liquidationBonusBps: BigNumberish,
      collateralEnabled: boolean,
      borrowEnabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  registerMarket: TypedContractMethod<
    [
      marketId: BytesLike,
      baseAsset: BytesLike,
      quoteAsset: BytesLike,
      maxLeverageBps: BigNumberish,
      maintenanceMarginBps: BigNumberish,
      takerFeeBps: BigNumberish,
      liquidationCloseFactorBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  repayDebt: TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMarketMode: TypedContractMethod<
    [marketId: BytesLike, active: boolean, reduceOnly: boolean],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[paused_: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferPosition: TypedContractMethod<
    [
      sourceSubAccount: BigNumberish,
      targetSubAccount: BigNumberish,
      marketId: BytesLike,
      portionBps: BigNumberish
    ],
    [AccountTypes.TransferReceiptStructOutput],
    "nonpayable"
  >;

  transferSequence: TypedContractMethod<[], [bigint], "view">;

  withdrawLiquidity: TypedContractMethod<
    [asset: BytesLike, shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  withdrawMargin: TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_COLLATERAL_FACTOR_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LEVERAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LIQUIDATION_BONUS_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_COLLATERAL_FACTOR_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LEVERAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accountSnapshot"
  ): TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [AccountTypes.AccountSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "accrueInterest"
  ): TypedContractMethod<[asset: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "addMargin"
  ): TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetConfig"
  ): TypedContractMethod<
    [asset: BytesLike],
    [AccountTypes.AssetConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<
    [
      subAccountId: BigNumberish,
      marketId: BytesLike,
      notionalValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collateralAssets"
  ): TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralBalance"
  ): TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish, asset: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectReserves"
  ): TypedContractMethod<
    [asset: BytesLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureAssetRisk"
  ): TypedContractMethod<
    [
      asset: BytesLike,
      collateralFactorBps: BigNumberish,
      liquidationThresholdBps: BigNumberish,
      liquidationBonusBps: BigNumberish,
      collateralEnabled: boolean,
      borrowEnabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureInterestRate"
  ): TypedContractMethod<
    [
      asset: BytesLike,
      baseRatePerSecond: BigNumberish,
      slope1PerSecond: BigNumberish,
      slope2PerSecond: BigNumberish,
      kinkUtilization: BigNumberish,
      reserveFactorBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "debtAssets"
  ): TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "debtOf"
  ): TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish, asset: BytesLike],
    [
      [bigint, bigint, bigint] & {
        principal: bigint;
        index: bigint;
        currentDebt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositLiquidity"
  ): TypedContractMethod<
    [asset: BytesLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositMargin"
  ): TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMarkets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike,
      seizeAsset: BytesLike,
      repayAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidityShares"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketConfig"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [AccountTypes.MarketConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "openPosition"
  ): TypedContractMethod<
    [
      subAccountId: BigNumberish,
      marketId: BytesLike,
      isLong: boolean,
      notionalValue: BigNumberish,
      collateralAsset: BytesLike,
      collateralAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolState"
  ): TypedContractMethod<
    [asset: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        cash: bigint;
        totalShares: bigint;
        totalBorrowDebt: bigint;
        borrowIndex: bigint;
        reserveBalance: bigint;
        utilization: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "positionMarkets"
  ): TypedContractMethod<
    [accountOwner: AddressLike, subAccountId: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "positionOf"
  ): TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike
    ],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        size: bigint;
        entryPrice: bigint;
        openNotional: bigint;
        unrealizedPnl: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewLiquidityWithdrawal"
  ): TypedContractMethod<
    [asset: BytesLike, shares: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteLiquidation"
  ): TypedContractMethod<
    [
      accountOwner: AddressLike,
      subAccountId: BigNumberish,
      marketId: BytesLike,
      seizeAsset: BytesLike,
      repayAmount: BigNumberish
    ],
    [AccountTypes.LiquidationQuoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      asset: BytesLike,
      token: AddressLike,
      decimals_: BigNumberish,
      collateralFactorBps: BigNumberish,
      liquidationThresholdBps: BigNumberish,
      liquidationBonusBps: BigNumberish,
      collateralEnabled: boolean,
      borrowEnabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerMarket"
  ): TypedContractMethod<
    [
      marketId: BytesLike,
      baseAsset: BytesLike,
      quoteAsset: BytesLike,
      maxLeverageBps: BigNumberish,
      maintenanceMarginBps: BigNumberish,
      takerFeeBps: BigNumberish,
      liquidationCloseFactorBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayDebt"
  ): TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMarketMode"
  ): TypedContractMethod<
    [marketId: BytesLike, active: boolean, reduceOnly: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[paused_: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferPosition"
  ): TypedContractMethod<
    [
      sourceSubAccount: BigNumberish,
      targetSubAccount: BigNumberish,
      marketId: BytesLike,
      portionBps: BigNumberish
    ],
    [AccountTypes.TransferReceiptStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferSequence"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<
    [asset: BytesLike, shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawMargin"
  ): TypedContractMethod<
    [subAccountId: BigNumberish, asset: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AssetRiskUpdated"
  ): TypedContractEvent<
    AssetRiskUpdatedEvent.InputTuple,
    AssetRiskUpdatedEvent.OutputTuple,
    AssetRiskUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DebtIncreased"
  ): TypedContractEvent<
    DebtIncreasedEvent.InputTuple,
    DebtIncreasedEvent.OutputTuple,
    DebtIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "DebtRepaid"
  ): TypedContractEvent<
    DebtRepaidEvent.InputTuple,
    DebtRepaidEvent.OutputTuple,
    DebtRepaidEvent.OutputObject
  >;
  getEvent(
    key: "InterestAccrued"
  ): TypedContractEvent<
    InterestAccruedEvent.InputTuple,
    InterestAccruedEvent.OutputTuple,
    InterestAccruedEvent.OutputObject
  >;
  getEvent(
    key: "InterestRateUpdated"
  ): TypedContractEvent<
    InterestRateUpdatedEvent.InputTuple,
    InterestRateUpdatedEvent.OutputTuple,
    InterestRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Liquidated"
  ): TypedContractEvent<
    LiquidatedEvent.InputTuple,
    LiquidatedEvent.OutputTuple,
    LiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityDeposited"
  ): TypedContractEvent<
    LiquidityDepositedEvent.InputTuple,
    LiquidityDepositedEvent.OutputTuple,
    LiquidityDepositedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityWithdrawn"
  ): TypedContractEvent<
    LiquidityWithdrawnEvent.InputTuple,
    LiquidityWithdrawnEvent.OutputTuple,
    LiquidityWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MarginDeposited"
  ): TypedContractEvent<
    MarginDepositedEvent.InputTuple,
    MarginDepositedEvent.OutputTuple,
    MarginDepositedEvent.OutputObject
  >;
  getEvent(
    key: "MarginWithdrawn"
  ): TypedContractEvent<
    MarginWithdrawnEvent.InputTuple,
    MarginWithdrawnEvent.OutputTuple,
    MarginWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MarketRegistered"
  ): TypedContractEvent<
    MarketRegisteredEvent.InputTuple,
    MarketRegisteredEvent.OutputTuple,
    MarketRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MarketUpdated"
  ): TypedContractEvent<
    MarketUpdatedEvent.InputTuple,
    MarketUpdatedEvent.OutputTuple,
    MarketUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PauseUpdated"
  ): TypedContractEvent<
    PauseUpdatedEvent.InputTuple,
    PauseUpdatedEvent.OutputTuple,
    PauseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionClosed"
  ): TypedContractEvent<
    PositionClosedEvent.InputTuple,
    PositionClosedEvent.OutputTuple,
    PositionClosedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "PositionTransferred"
  ): TypedContractEvent<
    PositionTransferredEvent.InputTuple,
    PositionTransferredEvent.OutputTuple,
    PositionTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveCollected"
  ): TypedContractEvent<
    ReserveCollectedEvent.InputTuple,
    ReserveCollectedEvent.OutputTuple,
    ReserveCollectedEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(bytes32,address,uint8)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "AssetRiskUpdated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      AssetRiskUpdatedEvent.InputTuple,
      AssetRiskUpdatedEvent.OutputTuple,
      AssetRiskUpdatedEvent.OutputObject
    >;
    AssetRiskUpdated: TypedContractEvent<
      AssetRiskUpdatedEvent.InputTuple,
      AssetRiskUpdatedEvent.OutputTuple,
      AssetRiskUpdatedEvent.OutputObject
    >;

    "DebtIncreased(address,uint256,bytes32,uint256,uint256)": TypedContractEvent<
      DebtIncreasedEvent.InputTuple,
      DebtIncreasedEvent.OutputTuple,
      DebtIncreasedEvent.OutputObject
    >;
    DebtIncreased: TypedContractEvent<
      DebtIncreasedEvent.InputTuple,
      DebtIncreasedEvent.OutputTuple,
      DebtIncreasedEvent.OutputObject
    >;

    "DebtRepaid(address,uint256,bytes32,uint256,uint256)": TypedContractEvent<
      DebtRepaidEvent.InputTuple,
      DebtRepaidEvent.OutputTuple,
      DebtRepaidEvent.OutputObject
    >;
    DebtRepaid: TypedContractEvent<
      DebtRepaidEvent.InputTuple,
      DebtRepaidEvent.OutputTuple,
      DebtRepaidEvent.OutputObject
    >;

    "InterestAccrued(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      InterestAccruedEvent.InputTuple,
      InterestAccruedEvent.OutputTuple,
      InterestAccruedEvent.OutputObject
    >;
    InterestAccrued: TypedContractEvent<
      InterestAccruedEvent.InputTuple,
      InterestAccruedEvent.OutputTuple,
      InterestAccruedEvent.OutputObject
    >;

    "InterestRateUpdated(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;
    InterestRateUpdated: TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;

    "Liquidated(address,address,uint256,bytes32,bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;
    Liquidated: TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;

    "LiquidityDeposited(address,bytes32,uint256,uint256)": TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;
    LiquidityDeposited: TypedContractEvent<
      LiquidityDepositedEvent.InputTuple,
      LiquidityDepositedEvent.OutputTuple,
      LiquidityDepositedEvent.OutputObject
    >;

    "LiquidityWithdrawn(address,bytes32,uint256,uint256)": TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;
    LiquidityWithdrawn: TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;

    "MarginDeposited(address,uint256,bytes32,uint256)": TypedContractEvent<
      MarginDepositedEvent.InputTuple,
      MarginDepositedEvent.OutputTuple,
      MarginDepositedEvent.OutputObject
    >;
    MarginDeposited: TypedContractEvent<
      MarginDepositedEvent.InputTuple,
      MarginDepositedEvent.OutputTuple,
      MarginDepositedEvent.OutputObject
    >;

    "MarginWithdrawn(address,uint256,bytes32,uint256)": TypedContractEvent<
      MarginWithdrawnEvent.InputTuple,
      MarginWithdrawnEvent.OutputTuple,
      MarginWithdrawnEvent.OutputObject
    >;
    MarginWithdrawn: TypedContractEvent<
      MarginWithdrawnEvent.InputTuple,
      MarginWithdrawnEvent.OutputTuple,
      MarginWithdrawnEvent.OutputObject
    >;

    "MarketRegistered(bytes32,bytes32,bytes32)": TypedContractEvent<
      MarketRegisteredEvent.InputTuple,
      MarketRegisteredEvent.OutputTuple,
      MarketRegisteredEvent.OutputObject
    >;
    MarketRegistered: TypedContractEvent<
      MarketRegisteredEvent.InputTuple,
      MarketRegisteredEvent.OutputTuple,
      MarketRegisteredEvent.OutputObject
    >;

    "MarketUpdated(bytes32,bool,bool)": TypedContractEvent<
      MarketUpdatedEvent.InputTuple,
      MarketUpdatedEvent.OutputTuple,
      MarketUpdatedEvent.OutputObject
    >;
    MarketUpdated: TypedContractEvent<
      MarketUpdatedEvent.InputTuple,
      MarketUpdatedEvent.OutputTuple,
      MarketUpdatedEvent.OutputObject
    >;

    "OracleUpdated(address,address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PauseUpdated(bool)": TypedContractEvent<
      PauseUpdatedEvent.InputTuple,
      PauseUpdatedEvent.OutputTuple,
      PauseUpdatedEvent.OutputObject
    >;
    PauseUpdated: TypedContractEvent<
      PauseUpdatedEvent.InputTuple,
      PauseUpdatedEvent.OutputTuple,
      PauseUpdatedEvent.OutputObject
    >;

    "PositionClosed(address,uint256,bytes32,int256,uint256,int256)": TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;
    PositionClosed: TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;

    "PositionOpened(address,uint256,bytes32,int256,uint256,uint256)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;

    "PositionTransferred(address,uint256,uint256,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PositionTransferredEvent.InputTuple,
      PositionTransferredEvent.OutputTuple,
      PositionTransferredEvent.OutputObject
    >;
    PositionTransferred: TypedContractEvent<
      PositionTransferredEvent.InputTuple,
      PositionTransferredEvent.OutputTuple,
      PositionTransferredEvent.OutputObject
    >;

    "ReserveCollected(bytes32,uint256,address)": TypedContractEvent<
      ReserveCollectedEvent.InputTuple,
      ReserveCollectedEvent.OutputTuple,
      ReserveCollectedEvent.OutputObject
    >;
    ReserveCollected: TypedContractEvent<
      ReserveCollectedEvent.InputTuple,
      ReserveCollectedEvent.OutputTuple,
      ReserveCollectedEvent.OutputObject
    >;
  };
}
