/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EquinoxLens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EquinoxLens__factory>;
    getContractFactory(
      name: "ExecutionCodec",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExecutionCodec__factory>;
    getContractFactory(
      name: "SettlementQueue",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SettlementQueue__factory>;
    getContractFactory(
      name: "EquinoxMarginProtocol",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EquinoxMarginProtocol__factory>;
    getContractFactory(
      name: "IEquinoxOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEquinoxOracle__factory>;
    getContractFactory(
      name: "IEquinoxToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEquinoxToken__factory>;
    getContractFactory(
      name: "FixedPoint",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedPoint__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "EquinoxOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EquinoxOracle__factory>;
    getContractFactory(
      name: "EquinoxERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EquinoxERC20__factory>;

    getContractAt(
      name: "EquinoxLens",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EquinoxLens>;
    getContractAt(
      name: "ExecutionCodec",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExecutionCodec>;
    getContractAt(
      name: "SettlementQueue",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SettlementQueue>;
    getContractAt(
      name: "EquinoxMarginProtocol",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EquinoxMarginProtocol>;
    getContractAt(
      name: "IEquinoxOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEquinoxOracle>;
    getContractAt(
      name: "IEquinoxToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEquinoxToken>;
    getContractAt(
      name: "FixedPoint",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedPoint>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "EquinoxOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EquinoxOracle>;
    getContractAt(
      name: "EquinoxERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EquinoxERC20>;

    deployContract(
      name: "EquinoxLens",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxLens>;
    deployContract(
      name: "ExecutionCodec",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExecutionCodec>;
    deployContract(
      name: "SettlementQueue",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementQueue>;
    deployContract(
      name: "EquinoxMarginProtocol",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxMarginProtocol>;
    deployContract(
      name: "IEquinoxOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEquinoxOracle>;
    deployContract(
      name: "IEquinoxToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEquinoxToken>;
    deployContract(
      name: "FixedPoint",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedPoint>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "EquinoxOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxOracle>;
    deployContract(
      name: "EquinoxERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxERC20>;

    deployContract(
      name: "EquinoxLens",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxLens>;
    deployContract(
      name: "ExecutionCodec",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExecutionCodec>;
    deployContract(
      name: "SettlementQueue",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementQueue>;
    deployContract(
      name: "EquinoxMarginProtocol",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxMarginProtocol>;
    deployContract(
      name: "IEquinoxOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEquinoxOracle>;
    deployContract(
      name: "IEquinoxToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEquinoxToken>;
    deployContract(
      name: "FixedPoint",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedPoint>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "EquinoxOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxOracle>;
    deployContract(
      name: "EquinoxERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EquinoxERC20>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
